import asyncio, edge_tts

VOICE = "en-US-GuyNeural"
RATE = "-8%"
PITCH = "-3Hz"

segments = {
    "dossiers_intro": "The Dossiers. Every name. Every connection. Every dollar. What follows is not speculation. It is a map of documented relationships, exposed in court filings, campaign finance records, SEC disclosures, and sworn congressional testimony. These are the people who built the machine. Some are in prison. Some are in the White House. Some are both, at different points in the same story.",

    "dossiers_sbf_circle": "The Bankman-Fried circle. Sam Bankman-Fried, son of two Stanford Law professors. MIT physics graduate. Jane Street quantitative trader. He built a thirty-two billion dollar empire in three years using stolen customer funds. His mother, Barbara Fried, ran Mind the Gap, one of the largest Democratic dark money operations in the country. His father, Joe Bankman, helped design the tax structure for FTX. They received twenty-six million dollars in real estate and cash from their son's company. His girlfriend, Caroline Ellison, became CEO of Alameda Research at twenty-eight years old. She managed billions in customer funds while maintaining a romantic relationship with the man who controlled those funds. Gary Wang, SBF's MIT roommate, wrote the single line of code that exempted Alameda from auto-liquidation, the backdoor that enabled the entire fraud. Nishad Singh funneled nine point seven million dollars in political donations as a straw donor. Ryan Salame, co-CEO of FTX Digital Markets, donated twenty-four million dollars to Republican causes. His girlfriend, Michelle Bond, ran for Congress using his money. The inner circle was small. The damage was eight billion dollars.",

    "dossiers_regulators": "The regulatory capture network. Gary Gensler spent eighteen years at Goldman Sachs, rising to partner and co-head of finance. He then taught a cryptocurrency course at MIT before becoming SEC Chairman. He met with Sam Bankman-Fried before the FTX collapse. He sued Coinbase, Binance, Kraken, and Gemini. Then the crypto industry spent two hundred and forty-five million dollars to remove him. He left on Inauguration Day. His replacement, Paul Atkins, has a net worth of three hundred and twenty-seven million dollars, with substantial cryptocurrency holdings. He co-chaired the Token Alliance, a crypto advocacy group. Within months of taking office, he dropped every major crypto enforcement case his predecessor had filed. Mark Wetjen went from CFTC Acting Chairman to FTX Head of Policy. He is the revolving door personified. Brian Brooks went from Office of the Comptroller of the Currency to CEO of Binance US. He quit after three months when he saw the books.",

    "dossiers_thiel": "Peter Thiel. PayPal co-founder. Palantir co-founder. The first outside investor in Facebook, turning five hundred thousand dollars into over one billion. Founders Fund partner. Bilderberg Group attendee. New Zealand citizen with a reported doomsday bunker. Thiel funded JD Vance's political career from the beginning, giving him his first venture capital job at Mithril Capital, then donating fifteen million dollars to his Senate campaign, then brokering his introduction to Donald Trump. Vance is now Vice President. Thiel's company Palantir saw its federal contracts nearly double from five hundred forty-one million to nine hundred seventy million dollars. The Army consolidated seventy-five contracts into a single ten-year deal worth up to ten billion. Former Palantir employees are embedded throughout the Department of Government Efficiency and the Department of Health and Human Services. David Sacks, PayPal's former COO, is now the White House AI and Crypto Czar, setting policy for the two industries in which Thiel is most heavily invested. One startup in nineteen ninety-nine produced six billionaires and the current architecture of American tech power.",

    "dossiers_musk": "Elon Musk. PayPal co-founder. CEO of Tesla, SpaceX, and xAI. Owner of X, formerly Twitter. Head of the Department of Government Efficiency. The largest individual political donor in American history at two hundred and eighty-eight million dollars in the twenty twenty-four cycle. His companies hold at least thirty-eight billion dollars in government contracts, loans, subsidies, and tax credits, according to a Washington Post investigation. As head of DOGE, Musk has cut staff, budgets, or contracts at all seven federal agencies where his companies hold contracts. He has terminated contracts for countless vendors. None of his own companies' contracts have been touched. SpaceX alone holds over twenty billion in historic government contracts. Tesla received seven point five billion in EV subsidies. Starlink provides internet to the Department of Defense. The man who controls the most government contracts in the private sector now controls the office that oversees government spending. The return on investment on his two hundred eighty-eight million dollar election spend is incalculable.",

    "dossiers_money_trail": "The money trail. Marc Andreessen and Ben Horowitz of Andreessen Horowitz, known as a16z, directed over one hundred million dollars to crypto PACs and published the Techno-Optimist Manifesto opposing AI regulation. Multiple a16z portfolio companies had their SEC cases dropped after inauguration. Brian Armstrong of Coinbase co-founded the Fairshake PAC and personally donated over twenty-five million dollars. Coinbase's SEC case was dropped. The Winklevoss twins of Gemini were the first major crypto donors to Trump at two million dollars. Their SEC case was dropped. Brad Garlinghouse of Ripple spent one hundred seventy-five million fighting the SEC. The case was dropped in twenty twenty-five. Then Ripple donated to the inauguration. The pattern is consistent across every company: donate to the campaign, attend the inauguration, get the enforcement action dismissed. The total cost of the donations is roughly two hundred forty-five million dollars. The total value of the dropped cases and favorable regulation is measured in the hundreds of billions.",

    "money_flow": "Follow the money. The cycle is simple and self-reinforcing. Step one: cryptocurrency companies accumulate billions from retail investors and trading fees. Step two: they spend two hundred forty-five million dollars on PAC donations, inauguration payments, and campaign contributions across both parties. Step three: their preferred candidates win and appoint industry allies to regulatory positions. Step four: those appointees drop enforcement actions, killing every pending case. Step five: the companies use the regulatory green light to expand operations, launch new products, and attract new investors. Step six: they accumulate more billions. The cycle repeats. Each revolution takes less time and generates more money than the last. The South Sea Bubble took years. Enron took a decade. The crypto capture of American regulation took ten months.",

    "revolving_door_full": "The revolving door. It spins in both directions, and it never stops. From government to industry: Jay Clayton, SEC Chairman, moved to One River Digital Asset Management. Elad Roisman, SEC Commissioner, became Chief Legal Officer at Millennium Management. Brett Redfearn, SEC Trading Director, went to become head of capital markets at Coinbase. From industry to government: Paul Atkins, crypto industry advocate, became SEC Chair. David Sacks, Craft Ventures partner, became AI and Crypto Czar. Bo Hines, aged twenty-nine, became Executive Director of the President's Digital Asset Advisory Board. Scott Bessent, who managed Soros Fund Management and had personal crypto holdings, became Treasury Secretary. From the defense sector, the pattern is identical. Lloyd Austin went from the Raytheon board to Secretary of Defense. Mark Esper went from Raytheon Vice President to Secretary of Defense, then back to defense consulting. The door doesn't just revolve. It accelerates.",

    "war_profiteers_names": "The war profiteers. Dick Cheney served as Secretary of Defense, then became CEO of Halliburton, earning forty-four million dollars in compensation. Then he became Vice President. Then Halliburton received thirty-nine point five billion dollars in Iraq-related contracts. The company moved its headquarters to Dubai. Donald Rumsfeld served twice as Secretary of Defense. Between tours, he invested heavily in Gilead Sciences, maker of Tamiflu. He then pushed for the Iraq invasion. Erik Prince founded Blackwater, the private military company that received over two billion dollars in government contracts. In September two thousand and seven, Blackwater guards killed seventeen Iraqi civilians at Nisour Square in Baghdad. Four guards were convicted. All four were pardoned by President Trump in December twenty twenty. Prince is the brother of Betsy DeVos, Trump's Secretary of Education. James Mattis served on the board of Theranos, the fraudulent blood-testing company, then became Secretary of Defense, then joined the board of General Dynamics, one of the largest defense contractors. The names change. The door keeps spinning.",

    "donors_2024": "The donors. Twenty twenty-four saw the largest concentration of political spending in American history. Elon Musk led with two hundred eighty-eight million dollars, the largest individual donation ever recorded. In return, he runs DOGE with access to every federal agency. Timothy Mellon, heir to the Mellon banking fortune, gave one hundred fifty million to the Make America Great Again PAC. Miriam Adelson, widow of casino magnate Sheldon Adelson, gave one hundred million in exchange for a reported promise regarding the Presidential Medal of Freedom, which she received. Marc Andreessen and Ben Horowitz directed over one hundred million to crypto PACs. Their portfolio companies had enforcement actions dropped. The Fairshake PAC, funded by Coinbase, Ripple, and Andreessen Horowitz, raised two hundred sixty million and won thirty-three of thirty-five races it entered. Sam Bankman-Fried, who donated seventy-three million in the twenty twenty-two cycle, is now serving twenty-five years in federal prison. The difference between him and the twenty twenty-four donors is not the strategy. It is the outcome. He got caught using stolen money. They used their own."
}

async def gen():
    for name, text in segments.items():
        print(f"Generating {name}...")
        comm = edge_tts.Communicate(text, VOICE, rate=RATE, pitch=PITCH)
        await comm.save(f"{name}.mp3")
        print(f"  Done: {name}.mp3")

asyncio.run(gen())
print("All 10 segments generated.")
